version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: counter-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
      MYSQL_USER: neko
      MYSQL_PASSWORD: neko
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend-app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  mysql-data:
