version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: counter-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
      MYSQL_USER: neko
      MYSQL_PASSWORD: neko
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: