version: "3.9"
services:
  mysql:
    image: mysql:8.4.5
    container_name: counter-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: counter
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
